### ISSUE TITLE
数据库文件有吗？

### ISSUE THREAD

**Issue by chinasonglei** [cmh1996/vue-mall#1]
后台的启动教程麻给一下，谢谢！

**Comment by cmh1996** [comment]
不好意思啊，暂不上传数据库文件，所以后台服务不能用。

**Comment by LongMr** [comment]
麻烦给下数据库脚本好吗

**Comment by LongMr** [comment]
管理后台的访问地址是什么呢？

**Comment by o-t-t** [comment]
你好 我现在很需要你的这份代码作为参考一下（没有用作其他用途，就是想作为参考，我正在写毕设，有点没有头绪，急需用来参考一下），能不能完整的给一份代码，包括数据库文件，能启动后台服务的能否私发我，QQ：1310794052  非常感谢

**Comment by chenAda** [comment]
你好，能提供数据库吗？就是参考下思路，目前比较急，可以的话能把整个发我qq826441180,谢谢

**Comment by cmh1996** [comment]
统一回复，如果大家想看数据库的各个表、有哪些列，大家可以看server/models下的代码，一个js文件就代表一个表。
