### ISSUE TITLE
大噶可以看看我改的版本，数据库啥的应该都没啥问题

### ISSUE THREAD

**Issue by yingpengsha** [cmh1996/vue-mall#15]
https://github.com/yingpengsha/vue-mall

**Comment by Hideer** [comment]
@yingpengsha 你好数据表方便给一套么

**Comment by yingpengsha** [comment]
> @yingpengsha 你好数据表方便给一套么

README 里面有写怎么生成

**Comment by banmax** [comment]
run server 那步可以详细说说吗，没看懂怎么run server，我敲这个命令告诉我找不到run命令

**Comment by yingpengsha** [comment]
> run server 那步可以详细说说吗，没看懂怎么run server，我敲这个命令告诉我找不到run命令@yingpengsha

**npm** run server

**Comment by Tierney2009** [comment]
> > 运行服务器那步可以详细说说吗，没看懂怎么运行服务器，我敲这个命令告诉我找到run命令@yingpengsha
> 
> **npm**运行服务器

前端启动错误 数据没有过来 显示不出图片

**Comment by yingpengsha** [comment]
> > > 运行服务器那步可以详细说说吗，没看懂怎么运行服务器，我敲这个命令告诉我找到run命令@yingpengsha
> > 
> > 
> > **npm**运行服务器
> 
> 前端启动错误 数据没有过来 显示不出图片

贴一下报错，不然我只能盲猜

**Comment by Tierney2009** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pengsha Ying"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午5:04
收件人:&nbsp;"cmh1996/vue-mall"<vue-mall@noreply.github.com&gt;;
抄送:&nbsp;"Tierney"<www.a21245452009@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cmh1996/vue-mall] 大噶可以看看我改的版本，数据库啥的应该都没啥问题 (#15)



   
运行服务器那步可以详细说说吗，没看懂怎么运行服务器，我敲这个命令告诉我找到run命令@yingpengsha
  
npm运行服务器
  
前端启动错误 数据没有过来 显示不出图片
  
贴一下报错，不然我只能盲猜

**Comment by Tierney2009** [comment]
> > > > 运行服务器那步可以详细说说吗，没看懂怎么运行服务器，我敲这个命令告诉我找到run命令@yingpengsha
> > > 
> > > 
> > > **npm**运行服务器
> > 
> > 
> > 前端启动错误数据没有过来显示不出图片
> 
> 贴一下运行信息​​或相关报



> > > > 运行服务器那步可以详细说说吗，没看懂怎么运行服务器，我敲这个命令告诉我找到run命令@yingpengsha
> > > 
> > > 
> > > **npm**运行服务器
> > 
> > 
> > 前端启动错误数据没有过来显示不出图片
> 
> 贴一下运行信息​​或相关报错，不然我只能盲猜
收到了吗带佬

**Comment by Tierney2009** [comment]
> > > > 运行服务器那步可以详细说说吗，没看懂怎么运行服务器，我敲这个命令告诉我找到run命令@yingpengsha
> > > 
> > > 
> > > **npm**运行服务器
> > 
> > 
> > 前端启动错误数据没有过来显示不出图片
> 
> 贴一下运行信息​​或相关报错，不然我只能盲猜

收到了吗

**Comment by yingpengsha** [comment]
我在哪看

**Comment by yingpengsha** [comment]
> 收到了吗

我在哪看？

**Comment by Tierney2009** [comment]
> > 收到了吗
> 
> 我在哪看？
![error](https://user-images.githubusercontent.com/49801987/70515872-08233180-1b71-11ea-8a14-5b192fa65616.png)

**Comment by yingpengsha** [comment]
> > > 收到了吗
> > 
> > 
> > 我在哪看？
> > ![error](https://user-images.githubusercontent.com/49801987/70515872-08233180-1b71-11ea-8a14-5b192fa65616.png)

不够，哪个页面，对应代码，直接发我邮箱好了。

**Comment by 4296SH** [comment]
> > 收到了吗
> 
> 我在哪看？



> > > > 收到了吗
> > > 
> > > 
> > > 我在哪看？
> > > ![error](https://user-images.githubusercontent.com/49801987/70515872-08233180-1b71-11ea-8a14-5b192fa65616.png)
> 
> 不够，哪个页面，对应代码，直接发我邮箱好了。

我也是这个问题，请问一下怎么解决，后台管理的账号密码是什么呀？

**Comment by yingpengsha** [comment]
> 我也是这个问题，请问一下怎么解决，后台管理的账号密码是什么呀？

后台账号密码在数据库自行添加，其他数据也是。上面报错信息是因为没有数据，有数据就没错了。

**Comment by Tierney2009** [comment]
在数据库里面添加一个密码------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>
发送时间: 2020年1月5日(星期天) 晚上6:07
收件人: "cmh1996/vue-mall"<vue-mall@noreply.github.com>;
抄送: "MichealZhang"<www.a21245452009@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cmh1996/vue-mall] 大噶可以看看我改的版本，数据库啥的应该都没啥问题 (#15)


 
我也是这个问题，请问一下怎么解决，后台管理的账号密码是什么呀？
  
后台账号密码在数据库自行添加，其他数据也是。上面报错信息是因为没有数据，有数据就没错了。
 
&mdash;

**Comment by 4296SH** [comment]
> 在数据库里面添加一个密码------------------ 原始邮件 ------------------ 发件人: "notifications"<notifications@github.com> 发送时间: 2020年1月5日(星期天) 晚上6:07 收件人: "cmh1996/vue-mall"<vue-mall@noreply.github.com>; 抄送: "MichealZhang"<[www.a21245452009@qq.com>;"Comment"<comment@noreply.github.com](http://www.a21245452009@qq.com>;%22Comment%22<comment@noreply.github.com)>; 主题: Re: [cmh1996/vue-mall] 大噶可以看看我改的版本，数据库啥的应该都没啥问题 (#15) 我也是这个问题，请问一下怎么解决，后台管理的账号密码是什么呀？ 后台账号密码在数据库自行添加，其他数据也是。上面报错信息是因为没有数据，有数据就没错了。 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，添加数据之后可以了，谢谢了

**Comment by 526088078** [comment]
> https://github.com/yingpengsha/vue-mall

大佬的你的可以跑起来，但是前端内容都是空的，商品图片什么的也都没有.怎么弄？

**Comment by yingpengsha** [comment]
> 大佬的你的可以跑起来，但是前端内容都是空的，商品图片什么的也都没有.怎么弄？

本来就没数据，要到后台添加

**Comment by test2g** [comment]
不过我是macOS mysql 8.0版本，
会有Unhandled rejection SequelizeDatabaseError: Got error 168 - 'Unknown (generic) error from engine' from storage engine报错
降又降不了，真的好烦
