### ISSUE TITLE
index报错

### ISSUE THREAD

**Issue by Jaden9527** [cmh1996/vue-mall#5]
[vue/no-unused-vars]'index' is defined but never used.   
![image](https://user-images.githubusercontent.com/36024802/38462194-281be7d6-3b15-11e8-8965-11c9d2400bb7.png)
index 为什么会报这种错

**Comment by cmh1996** [comment]
可能是新版本vue才会报这个错吧。他意思是没用到index但是代码中定义了index，你可以把index删了
