### ISSUE TITLE
怎么运行？

### ISSUE THREAD

**Issue by 814042432** [cmh1996/vue-mall#6]
麻烦能说说怎么运行起来？数据库脚本也没有呢？

**Comment by zw231212** [comment]
先运行server端的程序，再运行client端。
两边都要想npm install 安装库吧，然后看package里面的命令，npm run XXXX，如果获取不到数据的话可以看是不是前端配置url是不是正确的。
数据库你可以看另外一个issue，里面有脚本，应该能够跑起来一部分，我运行起来也会跳出一部分的bug，但是还是能够跑。
